settings:
  title: 'Status Page'
  url: 'https://status.zdaily.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog # unique identifier
    name: ZT Blog
    url: 'https://www.zdaily.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: vault
    name: VaultWarden
    url: 'https://vault.zdaily.net/'
    method: GET
    expectStatus: 200

  - id: chatgpt
    name: ChatGPT WebUI
    url: 'https://chat.zdaily.net'
    method: GET
    expectStatus: 200

  - id: tools
    name: IT Tools
    url: 'https://tools.zdaily.net/'
    method: GET
    expectStatus: 200
